<?php

namespace App\Filament\Resources\SKCKResource\Pages;

use App\Filament\Resources\SKCKResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateSKCK extends CreateRecord
{
    protected static string $resource = SKCKResource::class;

    //after save
    use \App\Traits\RedirectIndex;

    protected function afterCreate(): void
    {
        // Document will be generated by the resource's afterCreate method
    }

    protected function beforeSave(): void
    {
        dd('SKCK created successfully!');
    }
}
